using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[Serializable]
public class GenericObject 
{
    public string country;
    public string region;
    public string code;

    public int population_1975;
    public int arable_area_1975;
    public int energy_consumption_1975;
    public int gdp_per_capita_1975;
    public float life_expectancy_women_1975;
    public float life_expectancy_men_1975;
    public float life_expectancy_1975;
    public float infant_mortality_1975;
    public float number_personal_computer_1975;
    public float indexed_population_1975;
    public float indexed_energy_consumption_1975;
    public float index_gdp_1975;

    public int population_1976;
    public int arable_area_1976;
    public int energy_consumption_1976;
    public int gdp_per_capita_1976;
    public float life_expectancy_women_1976;
    public float life_expectancy_men_1976;
    public float life_expectancy_1976;
    public float infant_mortality_1976;
    public float number_personal_computer_1976;
    public float indexed_population_1976;
    public float indexed_energy_consumption_1976;
    public float index_gdp_1976;

    public int population_1977;
    public int arable_area_1977;
    public int energy_consumption_1977;
    public int gdp_per_capita_1977;
    public float life_expectancy_women_1977;
    public float life_expectancy_men_1977;
    public float life_expectancy_1977;
    public float infant_mortality_1977;
    public float number_personal_computer_1977;
    public float indexed_population_1977;
    public float indexed_energy_consumption_1977;
    public float index_gdp_1977;

    public int population_1978;
    public int arable_area_1978;
    public int energy_consumption_1978;
    public int gdp_per_capita_1978;
    public float life_expectancy_women_1978;
    public float life_expectancy_men_1978;
    public float life_expectancy_1978;
    public float infant_mortality_1978;
    public float number_personal_computer_1978;
    public float indexed_population_1978;
    public float indexed_energy_consumption_1978;
    public float index_gdp_1978;

    public int population_1979;
    public int arable_area_1979;
    public int energy_consumption_1979;
    public int gdp_per_capita_1979;
    public float life_expectancy_women_1979;
    public float life_expectancy_men_1979;
    public float life_expectancy_1979;
    public float infant_mortality_1979;
    public float number_personal_computer_1979;
    public float indexed_population_1979;
    public float indexed_energy_consumption_1979;
    public float index_gdp_1979;

    public int population_1980;
    public int arable_area_1980;
    public int energy_consumption_1980;
    public int gdp_per_capita_1980;
    public float life_expectancy_women_1980;
    public float life_expectancy_men_1980;
    public float life_expectancy_1980;
    public float infant_mortality_1980;
    public float number_personal_computer_1980;
    public float indexed_population_1980;
    public float indexed_energy_consumption_1980;
    public float index_gdp_1980;

    public int population_1981;
    public int arable_area_1981;
    public int energy_consumption_1981;
    public int gdp_per_capita_1981;
    public float life_expectancy_women_1981;
    public float life_expectancy_men_1981;
    public float life_expectancy_1981;
    public float infant_mortality_1981;
    public float number_personal_computer_1981;
    public float indexed_population_1981;
    public float indexed_energy_consumption_1981;
    public float index_gdp_1981;

    public int population_1982;
    public int arable_area_1982;
    public int energy_consumption_1982;
    public int gdp_per_capita_1982;
    public float life_expectancy_women_1982;
    public float life_expectancy_men_1982;
    public float life_expectancy_1982;
    public float infant_mortality_1982;
    public float number_personal_computer_1982;
    public float indexed_population_1982;
    public float indexed_energy_consumption_1982;
    public float index_gdp_1982;

    public int population_1983;
    public int arable_area_1983;
    public int energy_consumption_1983;
    public int gdp_per_capita_1983;
    public float life_expectancy_women_1983;
    public float life_expectancy_men_1983;
    public float life_expectancy_1983;
    public float infant_mortality_1983;
    public float number_personal_computer_1983;
    public float indexed_population_1983;
    public float indexed_energy_consumption_1983;
    public float index_gdp_1983;

    public int population_1984;
    public int arable_area_1984;
    public int energy_consumption_1984;
    public int gdp_per_capita_1984;
    public float life_expectancy_women_1984;
    public float life_expectancy_men_1984;
    public float life_expectancy_1984;
    public float infant_mortality_1984;
    public float number_personal_computer_1984;
    public float indexed_population_1984;
    public float indexed_energy_consumption_1984;
    public float index_gdp_1984;

    public int population_1985;
    public int arable_area_1985;
    public int energy_consumption_1985;
    public int gdp_per_capita_1985;
    public float life_expectancy_women_1985;
    public float life_expectancy_men_1985;
    public float life_expectancy_1985;
    public float infant_mortality_1985;
    public float number_personal_computer_1985;
    public float indexed_population_1985;
    public float indexed_energy_consumption_1985;
    public float index_gdp_1985;

    public int population_1986;
    public int arable_area_1986;
    public int energy_consumption_1986;
    public int gdp_per_capita_1986;
    public float life_expectancy_women_1986;
    public float life_expectancy_men_1986;
    public float life_expectancy_1986;
    public float infant_mortality_1986;
    public float number_personal_computer_1986;
    public float indexed_population_1986;
    public float indexed_energy_consumption_1986;
    public float index_gdp_1986;

    public int population_1987;
    public int arable_area_1987;
    public int energy_consumption_1987;
    public int gdp_per_capita_1987;
    public float life_expectancy_women_1987;
    public float life_expectancy_men_1987;
    public float life_expectancy_1987;
    public float infant_mortality_1987;
    public float number_personal_computer_1987;
    public float indexed_population_1987;
    public float indexed_energy_consumption_1987;
    public float index_gdp_1987;

    public int population_1988;
    public int arable_area_1988;
    public int energy_consumption_1988;
    public int gdp_per_capita_1988;
    public float life_expectancy_women_1988;
    public float life_expectancy_men_1988;
    public float life_expectancy_1988;
    public float infant_mortality_1988;
    public float number_personal_computer_1988;
    public float indexed_population_1988;
    public float indexed_energy_consumption_1988;
    public float index_gdp_1988;

    public int population_1989;
    public int arable_area_1989;
    public int energy_consumption_1989;
    public int gdp_per_capita_1989;
    public float life_expectancy_women_1989;
    public float life_expectancy_men_1989;
    public float life_expectancy_1989;
    public float infant_mortality_1989;
    public float number_personal_computer_1989;
    public float indexed_population_1989;
    public float indexed_energy_consumption_1989;
    public float index_gdp_1989;

    public int population_1990;
    public int arable_area_1990;
    public int energy_consumption_1990;
    public int gdp_per_capita_1990;
    public float life_expectancy_women_1990;
    public float life_expectancy_men_1990;
    public float life_expectancy_1990;
    public float infant_mortality_1990;
    public float number_personal_computer_1990;
    public float indexed_population_1990;
    public float indexed_energy_consumption_1990;
    public float index_gdp_1990;

    public int population_1991;
    public int arable_area_1991;
    public int energy_consumption_1991;
    public int gdp_per_capita_1991;
    public float life_expectancy_women_1991;
    public float life_expectancy_men_1991;
    public float life_expectancy_1991;
    public float infant_mortality_1991;
    public float number_personal_computer_1991;
    public float indexed_population_1991;
    public float indexed_energy_consumption_1991;
    public float index_gdp_1991;

    public int population_1992;
    public int arable_area_1992;
    public int energy_consumption_1992;
    public int gdp_per_capita_1992;
    public float life_expectancy_women_1992;
    public float life_expectancy_men_1992;
    public float life_expectancy_1992;
    public float infant_mortality_1992;
    public float number_personal_computer_1992;
    public float indexed_population_1992;
    public float indexed_energy_consumption_1992;
    public float index_gdp_1992;


    public int population_1993;
    public int arable_area_1993;
    public int energy_consumption_1993;
    public int gdp_per_capita_1993;
    public float life_expectancy_women_1993;
    public float life_expectancy_men_1993;
    public float life_expectancy_1993;
    public float infant_mortality_1993;
    public float number_personal_computer_1993;
    public float indexed_population_1993;
    public float indexed_energy_consumption_1993;
    public float index_gdp_1993;

    public int population_1994;
    public int arable_area_1994;
    public int energy_consumption_1994;
    public int gdp_per_capita_1994;
    public float life_expectancy_women_1994;
    public float life_expectancy_men_1994;
    public float life_expectancy_1994;
    public float infant_mortality_1994;
    public float number_personal_computer_1994;
    public float indexed_population_1994;
    public float indexed_energy_consumption_1994;
    public float index_gdp_1994;

    public int population_1995;
    public int arable_area_1995;
    public int energy_consumption_1995;
    public int gdp_per_capita_1995;
    public float life_expectancy_women_1995;
    public float life_expectancy_men_1995;
    public float life_expectancy_1995;
    public float infant_mortality_1995;
    public float number_personal_computer_1995;
    public float indexed_population_1995;
    public float indexed_energy_consumption_1995;
    public float index_gdp_1995;

    public int population_1996;
    public int arable_area_1996;
    public int energy_consumption_1996;
    public int gdp_per_capita_1996;
    public float life_expectancy_women_1996;
    public float life_expectancy_men_1996;
    public float life_expectancy_1996;
    public float infant_mortality_1996;
    public float number_personal_computer_1996;
    public float indexed_population_1996;
    public float indexed_energy_consumption_1996;
    public float index_gdp_1996;

    public int population_1997;
    public int arable_area_1997;
    public int energy_consumption_1997;
    public int gdp_per_capita_1997;
    public float life_expectancy_women_1997;
    public float life_expectancy_men_1997;
    public float life_expectancy_1997;
    public float infant_mortality_1997;
    public float number_personal_computer_1997;
    public float indexed_population_1997;
    public float indexed_energy_consumption_1997;
    public float index_gdp_1997;

    public int population_1998;
    public int arable_area_1998;
    public int energy_consumption_1998;
    public int gdp_per_capita_1998;
    public float life_expectancy_women_1998;
    public float life_expectancy_men_1998;
    public float life_expectancy_1998;
    public float infant_mortality_1998;
    public float number_personal_computer_1998;
    public float indexed_population_1998;
    public float indexed_energy_consumption_1998;
    public float index_gdp_1998;

    public int population_1999;
    public int arable_area_1999;
    public int energy_consumption_1999;
    public int gdp_per_capita_1999;
    public float life_expectancy_women_1999;
    public float life_expectancy_men_1999;
    public float life_expectancy_1999;
    public float infant_mortality_1999;
    public float number_personal_computer_1999;
    public float indexed_population_1999;
    public float indexed_energy_consumption_1999;
    public float index_gdp_1999;

    public int population_2000;
    public int arable_area_2000;
    public int energy_consumption_2000;
    public int gdp_per_capita_2000;
    public float life_expectancy_women_2000;
    public float life_expectancy_men_2000;
    public float life_expectancy_2000;
    public float infant_mortality_2000;
    public float number_personal_computer_2000;
    public float indexed_population_2000;
    public float indexed_energy_consumption_2000;
    public float index_gdp_2000;

}
